### ISSUE TITLE
Is it possible to recognize a free, occupied place in the mega cloud?

### ISSUE THREAD

**Issue by vukitoso** [t3rm1n4l/megacmd#101]
Hello.
Is it possible to recognize a free, occupied place in the mega cloud?

**Comment by ncw** [comment]
I don't understand what you mean - can you explain more?

**Comment by vukitoso** [comment]
> I don't understand what you mean - can you explain more?

It is required to find out how much total space is in the cloud and how much free space is left.
Via megacmd.

**Comment by ncw** [comment]
I don't think this is possible via megacmd. You can do this with [rclone](https://rclone.org) which supports mega using [rclone about](https://rclone.org/commands/rclone_about/).

I'm going to close this one since we aren't adding more features to megacmd.
