### ISSUE TITLE
File url after upload

### ISSUE THREAD

**Issue by A3G1S** [t3rm1n4l/megacmd#11]
Hey, 

Is it possible to get mega public url right after uploading a file via megacmd ?
Right Now I am opening mega site to get public url.

**Comment by sogko** [comment]
I've created a PR in ```go-mega``` library that enables generation of public download link. Hope it gets enough attention from @t3rm1n4l for a review and merge.

See: https://github.com/t3rm1n4l/go-mega/pull/10
