### ISSUE TITLE
Error when building under Wheezy

### ISSUE THREAD

**Issue by Papoulos** [t3rm1n4l/megacmd#57]
I'v DL the master.zip then unzip, then make.

But i hadn't the "golang" so i had the error :

make : go : unknown command.

After that i apt-get the gloang package and then I got that after a new "make" command :

go get github.com/t3rm1n4l/go-mega
# github.com/t3rm1n4l/go-mega

.gopath/src/github.com/t3rm1n4l/go-mega/utils.go:54: buf.Grow undefined (type _bytes.Buffer has no field or method Grow)
make: *_\* [build] Error 2

Any idea ?

Thanks.

**Comment by berezovskyi** [comment]
thanks a lot, it really helped. maybe in the README there should be a minimal Go version so that one can figure out if he needs to update the installation?
