### ISSUE TITLE
OpenBSD binaries

### ISSUE THREAD

**Issue by teratorn** [t3rm1n4l/megacmd#98]
Notice netbsd are provided but no openbsd. If it's not too hard to make them that would be nice. Thank you.

**Comment by ncw** [comment]
I made a new release with OpenBSD binaries for you :-)

You might want to have a go with [rclone which does supply an OpenBSD binary](https://rclone.org/downloads/) and it uses the same library that megacmd does and it is maintained.

**Comment by ncw** [comment]
I made a new release with OpenBSD binaries for you :-)

You might want to have a go with [rclone which does supply an OpenBSD binary](https://rclone.org/downloads/) and it uses the same library that megacmd does and it is maintained.

**Comment by ncw** [comment]
Bah, github seems to be having problems and the release hasn't uploaded :-(  WIll try again later

**Comment by ncw** [comment]
Open BSD binaries are now in the release :-)
